package org.example.kotlinlern.lesson24

class CatchException(message: String) : AssertionError(message)